# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/xiong/PycharmProjects/Serial_Y/main_ui.ui'
#
# Created: Mon Nov 21 16:52:12 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 2, 0, 1, 1)
        self.pushButton_LineClear = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_LineClear.setObjectName("pushButton_LineClear")
        self.gridLayout.addWidget(self.pushButton_LineClear, 2, 3, 1, 1)
        self.checkBox_LineShow = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_LineShow.setObjectName("checkBox_LineShow")
        self.gridLayout.addWidget(self.checkBox_LineShow, 2, 1, 1, 1)
        self.pushButton_LineUpdate = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_LineUpdate.setObjectName("pushButton_LineUpdate")
        self.gridLayout.addWidget(self.pushButton_LineUpdate, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_port = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_port.setObjectName("comboBox_port")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_port)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_baudrate = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.comboBox_baudrate.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_baudrate)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_parity = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.comboBox_parity.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_parity)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_bytesize = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_bytesize.setObjectName("comboBox_bytesize")
        self.comboBox_bytesize.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_bytesize)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_stopbits = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_stopbits.setObjectName("comboBox_stopbits")
        self.comboBox_stopbits.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_stopbits)
        self.pushButton_OpenSerial = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_OpenSerial.setObjectName("pushButton_OpenSerial")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_OpenSerial)
        self.label_SerialState = QtWidgets.QLabel(self.groupBox)
        self.label_SerialState.setObjectName("label_SerialState")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_SerialState)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName("formLayout_3")
        self.radioButton_RecvSetting_ASCII = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_RecvSetting_ASCII.setObjectName("radioButton_RecvSetting_ASCII")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButton_RecvSetting_ASCII)
        self.radioButton_RecvSetting_HEX = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_RecvSetting_HEX.setObjectName("radioButton_RecvSetting_HEX")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButton_RecvSetting_HEX)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_SendSetting_ASCII = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_SendSetting_ASCII.setObjectName("radioButton_SendSetting_ASCII")
        self.horizontalLayout.addWidget(self.radioButton_SendSetting_ASCII)
        self.radioButton_SendSetting_HEX = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_SendSetting_HEX.setObjectName("radioButton_SendSetting_HEX")
        self.horizontalLayout.addWidget(self.radioButton_SendSetting_HEX)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.checkBox_RepeatSend = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_RepeatSend.setObjectName("checkBox_RepeatSend")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_RepeatSend)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_RepeatSend_ms = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_RepeatSend_ms.setObjectName("lineEdit_RepeatSend_ms")
        self.horizontalLayout_2.addWidget(self.lineEdit_RepeatSend_ms)
        self.comboBox_s_ms = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_s_ms.setObjectName("comboBox_s_ms")
        self.comboBox_s_ms.addItem("")
        self.comboBox_s_ms.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_s_ms)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser_Recv = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_Recv.setObjectName("textBrowser_Recv")
        self.verticalLayout_2.addWidget(self.textBrowser_Recv)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_SendSerial = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_SendSerial.setObjectName("textEdit_SendSerial")
        self.horizontalLayout_3.addWidget(self.textEdit_SendSerial)
        self.pushButton_Send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.horizontalLayout_3.addWidget(self.pushButton_Send)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_matplot = QtWidgets.QVBoxLayout()
        self.verticalLayout_matplot.setObjectName("verticalLayout_matplot")
        self.horizontalLayout_4.addLayout(self.verticalLayout_matplot)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Button"))
        self.pushButton_clear.setText(_translate("MainWindow", "clear"))
        self.pushButton_LineClear.setText(_translate("MainWindow", "clear line"))
        self.checkBox_LineShow.setText(_translate("MainWindow", "line"))
        self.pushButton_LineUpdate.setText(_translate("MainWindow", "update line"))
        self.groupBox.setTitle(_translate("MainWindow", "Serial Setting"))
        self.label.setText(_translate("MainWindow", "port"))
        self.label_2.setText(_translate("MainWindow", "baudrate"))
        self.comboBox_baudrate.setItemText(0, _translate("MainWindow", "9600"))
        self.comboBox_baudrate.setItemText(1, _translate("MainWindow", "19200"))
        self.comboBox_baudrate.setItemText(2, _translate("MainWindow", "115200"))
        self.label_3.setText(_translate("MainWindow", "parity"))
        self.comboBox_parity.setItemText(0, _translate("MainWindow", "N"))
        self.label_4.setText(_translate("MainWindow", "bytesize"))
        self.comboBox_bytesize.setItemText(0, _translate("MainWindow", "8"))
        self.label_5.setText(_translate("MainWindow", "stopbits"))
        self.comboBox_stopbits.setItemText(0, _translate("MainWindow", "1"))
        self.pushButton_OpenSerial.setText(_translate("MainWindow", "open"))
        self.label_SerialState.setText(_translate("MainWindow", "state"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Recv Setting"))
        self.radioButton_RecvSetting_ASCII.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_RecvSetting_HEX.setText(_translate("MainWindow", "HEX"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Send Setting"))
        self.radioButton_SendSetting_ASCII.setText(_translate("MainWindow", "ASCII"))
        self.radioButton_SendSetting_HEX.setText(_translate("MainWindow", "HEX"))
        self.checkBox_RepeatSend.setText(_translate("MainWindow", "RepeatSend"))
        self.comboBox_s_ms.setItemText(0, _translate("MainWindow", "s"))
        self.comboBox_s_ms.setItemText(1, _translate("MainWindow", "ms"))
        self.pushButton_Send.setText(_translate("MainWindow", "send"))

